// =============================================================================
// PROJECT CHRONO - http://projectchrono.org
//
// Copyright (c) 2024 projectchrono.org
// All rights reserved.
//
// Use of this source code is governed by a BSD-style license that can be found
// in the LICENSE file at the top level of the distribution and at
// http://projectchrono.org/license-chrono.txt.
//
// =============================================================================
// Authors: Chrono Contributors
// =============================================================================
//
// SPH simulation of a combat helmet under blast loading from a C4 explosion.
//
// A combat helmet (rigid body with sphere approximation) is subjected to the
// blast wave generated by 14 kg of C4 explosive at a standoff distance of
// 6.1 m.  The explosion source is NOT modeled explicitly.  Instead, empirical
// formulas are used to characterise the blast wave:
//
//   * Hopkinson-Cranz scaled distance  Z = R / W_TNT^(1/3)
//   * Kinney & Graham (1985) formulas for peak overpressure (Pso) and
//     positive-phase duration (td)
//   * Friedlander equation for the pressure-time history:
//       P(t) = Pso * (1 - t/td) * exp(-b * t/td),   0 <= t <= td
//
// The blast wave is represented as a spatial initial-condition snapshot applied
// to the SPH air particles that surround the helmet at simulation time t = 0.
// Particles already in the blast region (x < 0, blast travelling in +x) are
// initialised with the Friedlander pressure and the corresponding particle
// velocity from the Rankine-Hugoniot approximation.  The SPH solver propagates
// the resulting pressure field and computes the forces on the helmet BCE
// markers.
//
// A CSV file "pressure_time_history.csv" is written to the output directory
// with columns:
//   time(s), P_friedlander(Pa), FSI_Fx(N), FSI_Fy(N), FSI_Fz(N),
//   helmet_pos_x(m), helmet_vel_x(m/s)
//
// Demo parameters correspond to:
//   - Explosive mass  : 14 kg C4
//   - TNT equivalence : 1.19  (mass basis)
//   - Standoff        : 6.1 m
//   - Blast direction : +X
//
// Reference values (Kinney & Graham 1985):
//   Z   ≈ 2.38 m/kg^(1/3)
//   Pso ≈ 138  kPa
//   td  ≈ 3.52 ms
// =============================================================================

#include <cassert>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <string>

#include "chrono/physics/ChSystemNSC.h"
#include "chrono/assets/ChVisualSystem.h"

#include "chrono_fsi/sph/ChFsiProblemSPH.h"

#ifdef CHRONO_VSG
    #include "chrono_fsi/sph/visualization/ChSphVisualizationVSG.h"
#endif

#ifdef CHRONO_POSTPROCESS
    #include "chrono_postprocess/ChGnuPlot.h"
#endif

#include "chrono_thirdparty/filesystem/path.h"
#include "chrono_thirdparty/cxxopts/ChCLI.h"

using namespace chrono;
using namespace chrono::fsi;
using namespace chrono::fsi::sph;

using std::cout;
using std::cerr;
using std::endl;

// =============================================================================
// Blast scenario parameters
// =============================================================================

// C4 charge
static const double g_charge_mass_kg = 14.0;   // mass of C4 charge (kg)
static const double g_tnt_equivalence = 1.19;   // C4-to-TNT mass equivalence

// Stand-off distance
static const double g_standoff_m = 6.1;         // stand-off distance (m)

// Atmospheric reference conditions
static const double g_P_atm   = 101325.0;       // atmospheric pressure (Pa)
static const double g_rho_air =      1.225;      // air density (kg/m^3)
static const double g_mu_air  =      1.8e-5;     // air dynamic viscosity (Pa·s)
static const double g_c_sound =    340.0;        // ambient speed of sound (m/s)
static const double g_gamma   =      1.4;        // heat capacity ratio (air)

// Helmet physical properties
static const double g_helmet_mass   =  1.5;      // helmet mass (kg)
static const double g_helmet_radius =  0.115;    // equivalent sphere radius (m)

// SPH domain dimensions (box centred at helmet origin)
static const double g_domain_L = 0.6;   // extent in X (blast direction)
static const double g_domain_W = 0.5;   // extent in Y
static const double g_domain_H = 0.5;   // extent in Z

// Visibility flags for the run-time visualiser
static bool g_show_rigid       = true;
static bool g_show_rigid_bce   = false;
static bool g_show_bndry_bce   = true;
static bool g_show_sph         = true;

// =============================================================================
// Empirical blast-wave formulas
// =============================================================================

/// Compute the Hopkinson-Cranz (cube-root) scaled distance.
/// @param R  Stand-off distance (m).
/// @param W  TNT-equivalent explosive mass (kg).
/// @return   Scaled distance Z (m/kg^(1/3)).
static double HopkinsonCranzZ(double R, double W) {
    return R / std::cbrt(W);
}

/// Peak side-on overpressure using Kinney & Graham (1985).
/// Valid for Z in [0.05, 40] m/kg^(1/3) (free-air spherical burst).
/// @param Z  Scaled distance (m/kg^(1/3)).
/// @return   Peak overpressure above ambient (Pa).
static double PeakOverpressure_KG(double Z) {
    double num = 808.0 * (1.0 + std::pow(Z / 4.5, 2));
    double d1  = std::sqrt(1.0 + std::pow(Z / 0.048, 2));
    double d2  = std::sqrt(1.0 + std::pow(Z / 0.32,  2));
    double d3  = std::sqrt(1.0 + std::pow(Z / 1.35,  2));
    return (num / (d1 * d2 * d3)) * g_P_atm;
}

/// Positive-phase duration using Kinney & Graham (1985).
/// @param Z      Scaled distance (m/kg^(1/3)).
/// @param W_tnt  TNT-equivalent mass (kg).
/// @return       Positive-phase duration (s).
static double PosDuration_KG(double Z, double W_tnt) {
    double Wcbrt   = std::cbrt(W_tnt);
    double num     = 980.0 * (1.0 + std::pow(Z / 0.54, 10.0));
    double d1      = 1.0 + std::pow(Z / 0.02, 3.0);
    double d2      = 1.0 + std::pow(Z / 0.74, 6.0);
    double d3      = std::sqrt(1.0 + std::pow(Z / 6.9, 2.0));
    return (num / (d1 * d2 * d3)) * Wcbrt * 1.0e-3;  // ms -> s
}

/// Positive-phase specific impulse using Kinney & Graham (1985).
/// @param Z      Scaled distance (m/kg^(1/3)).
/// @param W_tnt  TNT-equivalent mass (kg).
/// @return       Specific impulse (Pa·s).
static double SpecificImpulse_KG(double Z, double W_tnt) {
    double Wcbrt = std::cbrt(W_tnt);
    double num   = 0.067 * std::sqrt(1.0 + std::pow(Z / 0.23, 4.0));
    double den   = 1.0 + std::pow(Z / 1.55, 3.0);
    // Formula gives bar·ms/kg^(1/3); convert: 1 bar·ms = 1e5 Pa * 1e-3 s = 100 Pa·s
    return (num / den) * Wcbrt * 1.0e5 * 1.0e-3;
}

/// Friedlander equation: blast overpressure as a function of time.
/// P(t) = Pso * (1 - t/td) * exp(-b * t/td)   for 0 <= t <= td
/// @param t   Time after blast arrival at this location (s).
/// @param Pso Peak overpressure (Pa).
/// @param td  Positive-phase duration (s).
/// @param b   Decay (waveform) parameter (dimensionless).
/// @return    Overpressure (Pa); 0 outside [0, td].
static double FriedlanderPressure(double t, double Pso, double td, double b) {
    if (t < 0.0 || t > td)
        return 0.0;
    double tau = t / td;
    return Pso * (1.0 - tau) * std::exp(-b * tau);
}

/// Determine the Friedlander waveform parameter b so that the integrated
/// positive-phase impulse matches the Kinney & Graham specific impulse.
/// Uses bisection on  i_s(b) = Pso * td * [1/b - (1-exp(-b))/b^2].
/// @param Pso       Peak overpressure (Pa).
/// @param td        Positive-phase duration (s).
/// @param is_target Target specific impulse (Pa·s).
/// @return          Decay parameter b (>0).
static double ComputeFriedlanderB(double Pso, double td, double is_target) {
    auto impulse = [&](double b) {
        return Pso * td * (1.0 / b - (1.0 - std::exp(-b)) / (b * b));
    };
    double b_lo = 0.1, b_hi = 20.0;
    for (int k = 0; k < 120; ++k) {
        double b_mid = 0.5 * (b_lo + b_hi);
        if (impulse(b_mid) > is_target)
            b_lo = b_mid;
        else
            b_hi = b_mid;
        if (std::abs(b_hi - b_lo) < 1.0e-8)
            break;
    }
    return 0.5 * (b_lo + b_hi);
}

/// Approximate shock-front velocity from peak overpressure via
/// the Rankine-Hugoniot normal-shock relation (ideal gas, gamma = 1.4).
/// @param Pso  Peak overpressure above ambient (Pa).
/// @return     Shock-front speed (m/s).
static double ShockFrontSpeed(double Pso) {
    // From R-H: M_s = sqrt(1 + (gamma+1)/(2*gamma) * Pso/P_atm)
    // U_s = M_s * c_0
    double Ms = std::sqrt(1.0 + (g_gamma + 1.0) / (2.0 * g_gamma) * Pso / g_P_atm);
    return Ms * g_c_sound;
}

/// Particle velocity immediately behind the shock front (Rankine-Hugoniot).
/// @param Pso  Peak overpressure (Pa).
/// @param Us   Shock-front speed (m/s).
/// @return     Particle velocity (m/s) in the shock propagation direction.
static double ParticleVelocityBehindShock(double Pso, double Us) {
    return Pso / (g_rho_air * Us);
}

// =============================================================================
// Initial particle-property callback: spatial Friedlander snapshot
// =============================================================================

/// Set each SPH particle's initial pressure and velocity to the Friedlander
/// distribution at t = 0, when the blast front coincides with the helmet
/// origin.  The blast propagates in the +X direction.
///
/// For a particle at position (x, y, z):
///   t_eff = -x / Us   (time elapsed since the front passed this point)
///
/// Particles with x >= 0 have not yet been reached (t_eff <= 0 => P = 0).
/// Particles with x < 0 are in the decaying blast region (t_eff > 0).
class BlastInitialPressureCallback : public ChFsiProblemSPH::ParticlePropertiesCallback {
  public:
    BlastInitialPressureCallback(double Pso, double td, double b, double Us, double u_p)
        : m_Pso(Pso), m_td(td), m_b(b), m_Us(Us), m_u_p(u_p) {}

    virtual void set(const ChFsiFluidSystemSPH& sysSPH, const ChVector3d& pos) override {
        double t_eff = -pos.x() / m_Us;    // time since front passed (s)
        double P_over = FriedlanderPressure(t_eff, m_Pso, m_td, m_b);

        // Pressure and density (weakly compressible: ρ = ρ₀ + ΔP/c²)
        double c2 = sysSPH.GetSoundSpeed() * sysSPH.GetSoundSpeed();
        p0   = P_over;
        rho0 = sysSPH.GetDensity() + P_over / c2;
        mu0  = sysSPH.GetViscosity();

        // Particle velocity proportional to overpressure (decays as wave decays)
        double u = (P_over > 0.0) ? m_u_p * (P_over / m_Pso) : 0.0;
        v0 = ChVector3d(u, 0.0, 0.0);

        pre_pressure_scale0 = 1.01;  // small pre-pressure factor for SPH numerical stability
    }

  private:
    double m_Pso;  // peak overpressure (Pa)
    double m_td;   // positive-phase duration (s)
    double m_b;    // Friedlander decay parameter
    double m_Us;   // shock-front speed (m/s)
    double m_u_p;  // peak particle velocity (m/s)
};

// =============================================================================
// Command-line parsing
// =============================================================================

bool GetProblemSpecs(int argc,
                     char** argv,
                     double& t_end,
                     bool& verbose,
                     bool& output,
                     double& output_fps,
                     bool& render,
                     double& render_fps,
                     bool& snapshots) {
    ChCLI cli(argv[0], "FSI blast helmet demo");

    cli.AddOption<double>("Input", "t_end",
                          "Simulation duration [s]", std::to_string(t_end));

    cli.AddOption<bool>("Output", "quiet",
                        "Disable verbose terminal output");
    cli.AddOption<bool>("Output", "output",
                        "Enable collection of SPH output files");
    cli.AddOption<double>("Output", "output_fps",
                          "SPH output frequency [fps]", std::to_string(output_fps));

    cli.AddOption<bool>("Visualization", "no_vis",
                        "Disable run-time visualization");
    cli.AddOption<double>("Visualization", "render_fps",
                          "Render frequency [fps]", std::to_string(render_fps));
    cli.AddOption<bool>("Visualization", "snapshots",
                        "Enable writing snapshot images");

    if (!cli.Parse(argc, argv)) {
        cli.Help();
        return false;
    }

    t_end      = cli.GetAsType<double>("t_end");
    verbose    = !cli.GetAsType<bool>("quiet");
    output     = cli.GetAsType<bool>("output");
    output_fps = cli.GetAsType<double>("output_fps");
    render     = !cli.GetAsType<bool>("no_vis");
    render_fps = cli.GetAsType<double>("render_fps");
    snapshots  = cli.GetAsType<bool>("snapshots");

    return true;
}

// =============================================================================
// Main
// =============================================================================

int main(int argc, char* argv[]) {

    // -- SPH resolution & time-stepping
    const double initial_spacing = 0.025;   // m
    const double step_size       = 2.0e-5;  // s  (CFL satisfied for c_ref ~ 500 m/s)

    // -- Simulation duration: cover the full positive phase plus a margin
    double t_end      = 0.006;   // 6 ms
    bool   output     = false;
    double output_fps = 5000.0;
    bool   render     = true;
    double render_fps = 5000.0;
    bool   verbose    = true;
    bool   snapshots  = false;

    if (!GetProblemSpecs(argc, argv, t_end, verbose, output, output_fps,
                         render, render_fps, snapshots))
        return 1;

    // Meta-step (MBS <-> SPH communication interval)
    const double meta_step = 5.0 * step_size;

    // =========================================================================
    // 1.  Compute blast-wave parameters from empirical formulas
    // =========================================================================

    const double W_tnt = g_charge_mass_kg * g_tnt_equivalence;
    const double Z     = HopkinsonCranzZ(g_standoff_m, W_tnt);
    const double Pso   = PeakOverpressure_KG(Z);
    const double td    = PosDuration_KG(Z, W_tnt);
    const double is_kg = SpecificImpulse_KG(Z, W_tnt);
    const double b     = ComputeFriedlanderB(Pso, td, is_kg);
    const double Us    = ShockFrontSpeed(Pso);
    const double u_p   = ParticleVelocityBehindShock(Pso, Us);

    if (verbose) {
        cout << "\n=== Blast Wave Parameters (Kinney & Graham 1985) ===\n";
        cout << "  Charge              : " << g_charge_mass_kg << " kg C4\n";
        cout << "  TNT equivalent      : " << W_tnt << " kg\n";
        cout << "  Stand-off distance  : " << g_standoff_m << " m\n";
        cout << "  Scaled distance Z   : " << Z << " m/kg^(1/3)\n";
        cout << "  Peak overpressure   : " << Pso / 1.0e3 << " kPa ("
             << Pso / g_P_atm << " atm)\n";
        cout << "  Positive-phase dur. : " << td * 1.0e3 << " ms\n";
        cout << "  Specific impulse    : " << is_kg << " Pa·s\n";
        cout << "  Friedlander b param : " << b << "\n";
        cout << "  Shock-front speed   : " << Us << " m/s\n";
        cout << "  Peak particle vel.  : " << u_p << " m/s\n";
        cout << "====================================================\n\n";
    }

    // =========================================================================
    // 2.  Create the Chrono multi-body system
    // =========================================================================

    ChSystemNSC sysMBS;
    sysMBS.SetCollisionSystemType(ChCollisionSystem::Type::BULLET);

    // =========================================================================
    // 3.  Create the FSI / SPH problem
    // =========================================================================

    ChFsiProblemCartesian fsi(initial_spacing, &sysMBS);
    fsi.SetVerbose(verbose);
    auto sysFSI = fsi.GetFsiSystemSPH();

    // Blast is a short-duration horizontal load; gravity is negligible.
    fsi.SetGravitationalAcceleration(ChVector3d(0, 0, 0));

    fsi.SetStepSizeCFD(step_size);
    fsi.SetStepsizeMBD(step_size);

    // =========================================================================
    // 4.  Air (CFD) fluid properties
    // =========================================================================

    ChFsiFluidSystemSPH::FluidProperties fluid_props;
    fluid_props.density   = g_rho_air;
    fluid_props.viscosity = g_mu_air;
    fsi.SetCfdSPH(fluid_props);

    // =========================================================================
    // 5.  SPH method parameters
    //
    //  max_velocity drives the reference sound speed in the TAIT EOS.
    //  We set it to the shock-front speed so that c_ref ~ 10 * Us keeps density
    //  variations well below 1 %.
    // =========================================================================

    ChFsiFluidSystemSPH::SPHParameters sph_params;
    sph_params.integration_scheme  = IntegrationScheme::RK2;
    sph_params.num_bce_layers       = 3;
    sph_params.initial_spacing      = initial_spacing;
    sph_params.d0_multiplier        = 1.2;
    sph_params.max_velocity         = Us;   // shock-front speed (~450 m/s)
    sph_params.shifting_method      = ShiftingMethod::XSPH;
    sph_params.shifting_xsph_eps    = 0.5;
    sph_params.artificial_viscosity = 0.02;
    sph_params.eos_type             = EosType::TAIT;
    sph_params.use_consistent_gradient_discretization  = false;
    sph_params.use_consistent_laplacian_discretization = false;
    sph_params.num_proximity_search_steps = 1;
    sph_params.use_delta_sph          = true;
    sph_params.delta_sph_coefficient  = 0.1;
    sph_params.use_variable_time_step = false;
    sph_params.boundary_method        = BoundaryMethod::ADAMI;
    sph_params.viscosity_method       = ViscosityMethod::ARTIFICIAL_UNILATERAL;
    fsi.SetSPHParameters(sph_params);

    // =========================================================================
    // 6.  Helmet rigid body (spherical approximation)
    // =========================================================================

    // Moment of inertia of a solid sphere (conservative approximation)
    const double I_hel = 2.0 / 5.0 * g_helmet_mass * g_helmet_radius * g_helmet_radius;

    auto helmet = chrono_types::make_shared<ChBody>();
    helmet->SetName("helmet");
    helmet->SetPos(ChVector3d(0, 0, 0));
    helmet->SetRot(QUNIT);
    helmet->SetMass(g_helmet_mass);
    helmet->SetInertiaXX(ChVector3d(I_hel, I_hel, I_hel));
    helmet->SetFixed(false);
    helmet->EnableCollision(false);
    sysMBS.AddBody(helmet);

    // BCE geometry: sphere with helmet radius
    auto helmet_geo = chrono_types::make_shared<utils::ChBodyGeometry>();
    helmet_geo->materials.push_back(ChContactMaterialData());
    ChSphere hel_sphere(g_helmet_radius);
    helmet_geo->coll_spheres.push_back(
        utils::ChBodyGeometry::SphereShape(VNULL, hel_sphere, 0));

    if (g_show_rigid)
        helmet_geo->CreateVisualizationAssets(helmet, VisualizationType::COLLISION);

    // Register helmet with the FSI problem
    fsi.AddRigidBody(helmet, helmet_geo, /*check_embedded=*/true,
                     /*use_grid_bce=*/false);

    if (verbose) {
        cout << "Helmet rigid body:\n";
        cout << "  radius = " << g_helmet_radius << " m\n";
        cout << "  mass   = " << g_helmet_mass   << " kg\n";
        cout << "  I      = " << I_hel            << " kg·m²\n\n";
    }

    // =========================================================================
    // 7.  Blast-wave initial pressure & velocity on SPH particles
    // =========================================================================

    fsi.RegisterParticlePropertiesCallback(
        chrono_types::make_shared<BlastInitialPressureCallback>(
            Pso, td, b, Us, u_p));

    // =========================================================================
    // 8.  Construct the air SPH domain
    //
    //  The reference position for Construct() is the CENTRE OF THE BOTTOM FACE.
    //  Domain: X in [-L/2, L/2], Y in [-W/2, W/2], Z in [-H/2, H/2].
    //  Helmet at origin.  Blast travels in +X.
    //
    //  We use all six walls (BoxSide::ALL) to retain the air; wave reflections
    //  from the X boundaries are a known approximation for this local domain.
    // =========================================================================

    const ChVector3d box_size(g_domain_L, g_domain_W, g_domain_H);
    const ChVector3d box_ref(0.0, 0.0, -g_domain_H / 2.0);

    fsi.Construct(box_size, box_ref, BoxSide::ALL);

    // =========================================================================
    // 9.  Initialise the FSI system
    // =========================================================================

    fsi.Initialize();

    // =========================================================================
    // 10.  Output directories
    // =========================================================================

    const std::string out_dir = GetChronoOutputPath() + "FSI_Blast_Helmet/";
    if (!filesystem::create_directory(filesystem::path(out_dir))) {
        cerr << "Error creating directory " << out_dir << "\n";
        return 1;
    }

    if (output) {
        for (const auto& sub : {"particles", "fsi"}) {
            if (!filesystem::create_directory(filesystem::path(out_dir + sub))) {
                cerr << "Error creating directory " << out_dir + sub << "\n";
                return 1;
            }
        }
    }

    if (!filesystem::create_directory(filesystem::path(out_dir + "snapshots"))) {
        cerr << "Error creating directory " << out_dir + "snapshots\n";
        return 1;
    }

    // =========================================================================
    // 11.  CSV output: pressure-time history at helmet surface
    // =========================================================================

    std::ofstream csv(out_dir + "pressure_time_history.csv", std::ios::trunc);
    csv << "time_s,"
           "P_friedlander_Pa,"
           "reflected_pressure_Pa,"
           "FSI_Fx_N,FSI_Fy_N,FSI_Fz_N,"
           "helmet_pos_x_m,helmet_vel_x_ms\n";

    // =========================================================================
    // 12.  Run-time visualisation (optional, requires Chrono::VSG)
    // =========================================================================

    std::shared_ptr<ChVisualSystem> vis;

#ifdef CHRONO_VSG
    if (render) {
        // Colour SPH particles by pressure: range [0, 2*Pso]
        auto col_cb = chrono_types::make_shared<ParticlePressureColorCallback>(
            0.0, 2.0 * Pso, /*bimodal=*/false);

        auto visFSI = chrono_types::make_shared<ChSphVisualizationVSG>(sysFSI.get());
        visFSI->EnableFluidMarkers(g_show_sph);
        visFSI->EnableBoundaryMarkers(g_show_bndry_bce);
        visFSI->EnableRigidBodyMarkers(g_show_rigid_bce);
        visFSI->SetSPHColorCallback(col_cb, ChColormap::Type::HOT);

        auto visVSG = chrono_types::make_shared<vsg3d::ChVisualSystemVSG>();
        visVSG->AttachPlugin(visFSI);
        visVSG->AttachSystem(&sysMBS);
        visVSG->SetWindowTitle(
            "Helmet Blast SPH  (14 kg C4 @ 6.1 m)");
        visVSG->SetWindowSize(1280, 800);
        visVSG->SetWindowPosition(100, 100);
        visVSG->AddCamera(
            ChVector3d(1.5 * g_domain_L, 0.0, 0.5 * g_domain_H),
            ChVector3d(0, 0, 0));
        visVSG->SetLightIntensity(0.9f);
        visVSG->SetLightDirection(CH_PI_2, CH_PI / 6);

        visVSG->Initialize();
        vis = visVSG;
    }
#else
    render = false;
#endif

    // =========================================================================
    // 13.  Simulation loop
    // =========================================================================

    if (verbose) {
        cout << "Starting simulation:\n";
        cout << "  t_end   = " << t_end * 1.0e3 << " ms\n";
        cout << "  dt_CFD  = " << step_size * 1.0e6 << " µs\n";
        cout << "  N_SPH   = " << fsi.GetNumSPHParticles() << "\n";
        cout << "  N_BCE   = " << fsi.GetNumBCE(helmet) << "  (helmet BCE)\n\n";
    }

    double time        = 0.0;
    int    sim_frame   = 0;
    int    out_frame   = 0;
    int    rend_frame  = 0;

    ChTimer timer;
    timer.start();

    while (time < t_end) {

        // -- Friedlander pressure at current time (for logging)
        double P_fried = FriedlanderPressure(time, Pso, td, b);

        // -- Reflected overpressure (normal incidence, Rankine-Hugoniot)
        //    Pr = Pso * 2*(2*gamma*Pso + (3*gamma-1)*P_atm) /
        //                ((gamma-1)*Pso + 2*gamma*P_atm)
        //    For the log, scale by P_fried/Pso to apply at current time.
        double Pr_peak = Pso * 2.0 * (2.0 * g_gamma * Pso +
                                       (3.0 * g_gamma - 1.0) * g_P_atm) /
                         ((g_gamma - 1.0) * Pso + 2.0 * g_gamma * g_P_atm);
        double P_refl  = (Pso > 0.0) ? Pr_peak * (P_fried / Pso) : 0.0;

        // -- FSI force on helmet BCE markers
        const auto& fsi_force = fsi.GetFsiBodyForce(helmet);

        // -- Write CSV row
        csv << time << ","
            << P_fried << ","
            << P_refl  << ","
            << fsi_force.x() << "," << fsi_force.y() << "," << fsi_force.z() << ","
            << helmet->GetPos().x() << ","
            << helmet->GetLinVel().x()
            << "\n";

        // -- Console output every 50 meta-steps
        if (verbose && sim_frame % 50 == 0) {
            cout << "  t = " << std::fixed << std::setprecision(3)
                 << time * 1.0e3 << " ms"
                 << "  P_Fried = " << std::setprecision(1) << P_fried / 1.0e3 << " kPa"
                 << "  FSI_Fx = "  << std::setprecision(2) << fsi_force.x() << " N"
                 << "  x_helmet = " << std::setprecision(4)
                 << helmet->GetPos().x() * 1.0e3 << " mm\n";
        }

        // -- SPH particle data output
        if (output && time >= out_frame / output_fps) {
            fsi.SaveOutputData(time,
                               out_dir + "particles",
                               out_dir + "fsi");
            ++out_frame;
        }

        // -- Visualisation
#ifdef CHRONO_VSG
        if (render && time >= rend_frame / render_fps) {
            if (!vis->Run())
                break;
            vis->Render();

            if (snapshots) {
                std::ostringstream fname;
                fname << out_dir << "snapshots/img_"
                      << std::setw(5) << std::setfill('0') << rend_frame + 1
                      << ".bmp";
                vis->WriteImageToFile(fname.str());
            }
            ++rend_frame;
        }
#endif

        // -- Advance FSI dynamics
        fsi.DoStepDynamics(meta_step);
        time += meta_step;
        ++sim_frame;
    }

    timer.stop();
    csv.close();

    // =========================================================================
    // 14.  Summary
    // =========================================================================

    if (verbose) {
        cout << "\n=== Simulation Summary ===\n";
        cout << "  Wall-clock time : " << timer() << " s\n";
        cout << "  Simulated time  : " << t_end * 1.0e3 << " ms\n";
        cout << "  Helmet final pos: " << helmet->GetPos() << " m\n";
        cout << "  Helmet final vel: " << helmet->GetLinVel() << " m/s\n";
        cout << "  CSV output      : " << out_dir << "pressure_time_history.csv\n";
        cout << "==========================\n\n";
    }

#ifdef CHRONO_POSTPROCESS
    // Optional: plot Friedlander pressure-time history using GnuPlot
    {
        postprocess::ChGnuPlot gp(out_dir + "friedlander.gpl");
        gp.SetGrid();
        gp.SetTitle("Helmet Surface Pressure-Time History (14 kg C4 at 6.1 m)");
        gp.SetLabelX("time (s)");
        gp.SetLabelY("pressure (Pa)");
        // Column 1 = time (s), column 2 = Friedlander overpressure (Pa)
        gp.Plot(out_dir + "pressure_time_history.csv", 1, 2,
                "Friedlander P",
                " with lines lw 2 lc rgb '#CC3333'");
    }
#endif

    return 0;
}
